---
# tasks file for polychromatic - Ubuntu

- name: Install python3-apt on Ubuntu systems, required for package_facts.
  apt:
    name: python3-apt
    state: present
    force_apt_get: yes
    update_cache: yes
# - name: Gather package facts to verify if openrazer is installed as it is a dependency.
#   package_facts:
#     manager: apt
- name: Add openrazer repo on Ubuntu systems. Dependency of polychromatic.
  apt_repository:
    repo: 'ppa:openrazer/stable'
    state: present
    filename: openrazer
    codename: "{{ ansible_lsb['codename'] }}"
    update_cache: yes
  # when: packages['openrazer-meta'] is not defined
- name: Install openrazer on Ubuntu systems.
  apt:
    name: openrazer-meta
    state: present
    force_apt_get: yes
  # when: packages['openrazer-meta'] is not defined
- name: Adding repository {{ polychromatic_repo }} on Ubuntu systems
  apt_repository:
    repo: "{{ polychromatic_repo }}"
    state: "{{ polychromatic_repo_desired_state }}"
    filename: "{{ polychromatic_repo_filename }}"
    codename: "{{ ansible_lsb['codename'] }}"
    update_cache: yes
- name: Installing {{ polychromatic_app }} on Ubuntu systems
  apt:
    name: "{{ polychromatic_app }}"
    state: "{{ polychromatic_package_desired_state }}"
    force_apt_get: yes
    update_cache: yes
